# Drafts release notes as pull requests are merged into main
# 
# More Details:
# https://probot.github.io/apps/release-drafter/

name-template: v$NEXT_PATCH_VERSION
tag-template: v$NEXT_PATCH_VERSION
categories:
  - title: 🚀 Features
    label: feature
  - title: 🐛 Bug Fixes
    label: fix
  - title: 🧰 Maintenance
    label: maintenance
# tag-template: - $TITLE @$AUTHOR (#$NUMBER)

template: |
  ## Changes
  
  $CHANGES
  
